-- Portable MariaDB 10.6+ CMS foundation. Apply only through the approved
-- migration process; this file is not executed by the public web app.
CREATE TABLE cms_users (id CHAR(36) PRIMARY KEY, username VARCHAR(128) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE cms_roles (id CHAR(36) PRIMARY KEY, code VARCHAR(64) NOT NULL UNIQUE, title VARCHAR(128) NOT NULL);
CREATE TABLE cms_user_roles (user_id CHAR(36) NOT NULL, role_id CHAR(36) NOT NULL, PRIMARY KEY(user_id, role_id), FOREIGN KEY(user_id) REFERENCES cms_users(id), FOREIGN KEY(role_id) REFERENCES cms_roles(id));
CREATE TABLE cms_documents (id CHAR(36) PRIMARY KEY, kind VARCHAR(64) NOT NULL, slug VARCHAR(160) NOT NULL, locale VARCHAR(16) NOT NULL DEFAULT 'fa-IR', status VARCHAR(24) NOT NULL DEFAULT 'draft', published_revision_id CHAR(36) NULL, created_by CHAR(36) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY cms_document_slug(kind, slug, locale));
CREATE TABLE cms_document_revisions (id CHAR(36) PRIMARY KEY, document_id CHAR(36) NOT NULL, revision_no INT NOT NULL, body_json JSON NOT NULL, seo_json JSON NULL, change_note VARCHAR(500) NULL, created_by CHAR(36) NOT NULL, created_at DATETIME NOT NULL, UNIQUE KEY cms_revision(document_id, revision_no), FOREIGN KEY(document_id) REFERENCES cms_documents(id));
CREATE TABLE cms_navigation_items (id CHAR(36) PRIMARY KEY, location VARCHAR(32) NOT NULL, label VARCHAR(80) NOT NULL, href VARCHAR(300) NOT NULL, sort_order INT NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'draft', revision_no INT NOT NULL DEFAULT 1, updated_by CHAR(36) NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE cms_media (id CHAR(36) PRIMARY KEY, storage_key VARCHAR(500) NOT NULL UNIQUE, mime_type VARCHAR(120) NOT NULL, bytes BIGINT NOT NULL, alt_text VARCHAR(300) NULL, rights_status VARCHAR(32) NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'draft', uploaded_by CHAR(36) NOT NULL, created_at DATETIME NOT NULL);
CREATE TABLE cms_redirects (id CHAR(36) PRIMARY KEY, source_path VARCHAR(500) NOT NULL UNIQUE, destination_path VARCHAR(500) NOT NULL, status_code SMALLINT NOT NULL DEFAULT 308, status VARCHAR(24) NOT NULL DEFAULT 'published', updated_by CHAR(36) NOT NULL, updated_at DATETIME NOT NULL);
CREATE TABLE cms_audit_events (id CHAR(36) PRIMARY KEY, actor_id CHAR(36) NOT NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(64) NOT NULL, entity_id CHAR(36) NOT NULL, before_json JSON NULL, after_json JSON NULL, reason VARCHAR(500) NULL, created_at DATETIME NOT NULL, KEY cms_audit_entity(entity_type, entity_id, created_at));
