"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, Bell, CarFront, CircleCheck, CircleX, FileText, Headphones, LayoutDashboard, LockKeyhole, Search, ShieldCheck, Tags, UsersRound } from "lucide-react";
import { entries, faNumber, vehicleName, vehicles } from "@/lib/mehr-site/data";
import { AdminVehicleEditor } from "./admin-vehicle-editor";
import { AdminNavigationStudio } from "./admin-navigation-studio";
import { AdminContentStudio } from "./admin-content-studio";
import { AdminMediaLibrary } from "./admin-media-library";

type Tab = "overview" | "catalog" | "content" | "support" | "customer" | "seo" | "security";
const tabs: { id: Tab; label: string; icon: typeof LayoutDashboard }[] = [
  { id: "overview", label: "نمای کلی", icon: LayoutDashboard }, { id: "catalog", label: "خودروها", icon: CarFront },
  { id: "content", label: "محتوا و رسانه", icon: FileText }, { id: "support", label: "پشتیبانی", icon: Headphones },
  { id: "customer", label: "تجربه مشتری", icon: UsersRound }, { id: "seo", label: "SEO و انتشار", icon: Tags },
  { id: "security", label: "دسترسی و اتصال", icon: ShieldCheck },
];
const readiness = [
  ["کاتالوگ و صفحات عمومی", "آماده برای بازبینی", "ok"], ["ارسال درخواست بازدید و معاوضه", "تا اتصال BFF فقط پیش‌نویس", "warn"],
  ["پرونده، ویدیو و مدارک مشتری", "نیازمند OTP، مالکیت و فضای فایل خصوصی", "locked"], ["انتشار موتور جست‌وجو", "تا تأیید دامنه و Search Console بسته", "locked"],
] as const;

function State({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral" | "ok" | "warn" | "locked" }) { return <span className={`ma-state is-${tone}`}>{children}</span>; }

export function MehrAdminConsole({ username }: { username: string }) {
  const [tab, setTab] = useState<Tab>("overview");
  const [query, setQuery] = useState("");
  const cars = useMemo(() => vehicles.filter(car => vehicleName(car).toLowerCase().includes(query.trim().toLowerCase())), [query]);
  const publicEntries = entries.filter(entry => entry.contentStatus === "official_public_content");
  return <main className="ma-shell">
    <aside className="ma-sidebar"><Link href="/mehr" className="ma-brand"><img src="/brand/mehr-symbol.png" alt="نشان مهر" width={38} height={38}/><span><b>مهر خودرو</b><small>OPERATOR CONSOLE · LOCAL</small></span></Link><nav aria-label="بخش‌های کنسول">{tabs.map(item => <button key={item.id} type="button" className={tab === item.id ? "is-active" : ""} onClick={() => setTab(item.id)}><item.icon size={18}/>{item.label}</button>)}</nav><div className="ma-sidebar-note"><LockKeyhole size={17}/><span>این نسخه فقط روی محیط محلی باز می‌شود و هیچ داده مشتری در آن بارگذاری نشده است.</span></div></aside>
    <section className="ma-main"><header className="ma-header"><div><span className="ma-eyebrow">MEHR / INTERNAL WORKSPACE</span><h1>{tabs.find(item => item.id === tab)?.label}</h1></div><div className="ma-header-actions"><State tone="ok">{username}</State><Link href="/mehr" className="ma-public-link">مشاهده سایت<ArrowLeft size={16}/></Link><form action="/mehr/admin/logout" method="post"><button className="ma-logout" type="submit">خروج</button></form></div></header>
      {tab === "overview" && <Overview publicEntries={publicEntries.length}/>}
      {tab === "catalog" && <Catalog query={query} setQuery={setQuery} cars={cars}/>}
      {tab === "content" && <Content publicEntries={publicEntries.length}/>}
      {tab === "support" && <Support/>}{tab === "customer" && <Customer/>}{tab === "seo" && <Seo/>}{tab === "security" && <Security/>}
    </section>
  </main>;
}

function Overview({ publicEntries }: { publicEntries: number }) { return <><section className="ma-hero"><div><span className="ma-eyebrow">CONTROL TOWER</span><h2>همه‌چیز برای اداره سایت،<br/>بدون عبور از مرز داده مشتری.</h2><p>این میزکار وضعیت محتوای عمومی و آمادگی اتصال‌ها را یکجا نشان می‌دهد. عملیات حساس تا زمان اتصال امن، فقط «نیازمند اتصال» می‌مانند.</p></div><div className="ma-hero-mark">MEHR<br/><em>ADMIN</em></div></section><section className="ma-stats"><Metric icon={CarFront} value={faNumber(vehicles.length)} label="مدل در کاتالوگ عمومی"/><Metric icon={FileText} value={faNumber(publicEntries)} label="محتوای رسمی قابل نمایش"/><Metric icon={Bell} value="۰" label="درخواست واقعی در این محیط"/><Metric icon={Headphones} value="۰" label="تیکت واقعی در این محیط"/></section><section className="ma-grid"><div className="ma-panel ma-wide"><div className="ma-panel-head"><div><span className="ma-eyebrow">READINESS</span><h2>آمادگی قابلیت‌ها</h2></div><State>محیط توسعه</State></div><div className="ma-readiness">{readiness.map(([title, detail, tone]) => <div key={title}><span className="ma-dot"/><div><strong>{title}</strong><small>{detail}</small></div><State tone={tone}>{tone === "ok" ? "بازبینی" : tone === "warn" ? "اتصال لازم" : "محافظت‌شده"}</State></div>)}</div></div><div className="ma-panel"><span className="ma-eyebrow">RULE OF THE DAY</span><h2>اول مالکیت، بعد نمایش</h2><p>VIN، ویدیوی اختصاصی، مدارک و وضعیت قرارداد فقط پس از OTP، تطبیق مالکیت و سیاست انتشار سمت سرور قابل ارائه‌اند.</p><Link href="/mehr/my-car" className="ma-inline-link">مشاهده ورودی پرتال<ArrowLeft size={16}/></Link></div></section></> }
function Metric({ icon: Icon, value, label }: { icon: typeof CarFront; value: string; label: string }) { return <div className="ma-metric"><Icon size={21}/><b>{value}</b><span>{label}</span></div>; }
function Catalog({ query, setQuery, cars }: { query: string; setQuery: (value: string) => void; cars: typeof vehicles }) { return <><section className="ma-intro"><h2>کاتالوگ عمومی</h2><p>این فهرست فقط از داده‌های عمومی سایت ساخته می‌شود؛ قیمت، موجودی یا جزئیات داخلی در آن وجود ندارد.</p></section><label className="ma-search"><Search size={18}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="جست‌وجوی مدل"/></label><section className="ma-list">{cars.map(car => <article key={car.slug}><img src={`/mehr-site/vehicles/${car.slug}.${car.primaryImage.url.split(".").pop()?.split("?")[0] || "png"}`} alt=""/><div><span>{car.brandName}</span><h2>{vehicleName(car)}</h2><p>{car.specs.body.join(" · ")} · {car.specs.year.join(" / ")}</p></div><State tone="ok"><CircleCheck size={14}/>عمومی</State><Link href={`/mehr/cars/${car.slug}`} aria-label={`نمایش ${vehicleName(car)}`}><ArrowLeft size={18}/></Link></article>)}</section>{!cars.length && <p className="ma-empty">مدلی با این نام پیدا نشد.</p>}<AdminVehicleEditor/></> }
function Content({ publicEntries }: { publicEntries: number }) { return <><section className="ma-intro"><h2>محتوا و رسانه</h2><p>رسانه‌های عمومی باید مجوز استفاده، ارتباط با مدل و نسخه مناسب موبایل داشته باشند. ویدیوی شخصی مشتری در این بخش نمایش داده نمی‌شود.</p></section><section className="ma-grid"><div className="ma-panel"><b className="ma-number">{faNumber(publicEntries)}</b><h2>محتوای رسمی واردشده</h2><p>مطالب، اطلاعیه‌ها، خدمات و صفحات راهنمای واردات از CMS نسخه‌دار خوانده می‌شوند.</p></div><div className="ma-panel"><b className="ma-number">۰</b><h2>فایل خصوصی در مرورگر</h2><p>صفر باید بماند؛ برای مدارک و ویدیو، object storage خصوصی و لینک کوتاه‌عمر لازم است.</p></div><div className="ma-panel"><b className="ma-number">۰</b><h2>صف انتشار‌نیافته</h2><p>پیش‌نویس‌های صفحه، خبر، خدمات و راهنمای واردات در Content Studio قابل بازبینی هستند.</p></div></section><AdminContentStudio/><AdminMediaLibrary/><AdminNavigationStudio/><section className="ma-panel ma-callout"><FileText size={24}/><div><h2>گردش انتشار</h2><p>پیش‌نویس → بازبینی محتوا و حقوق رسانه → تأیید مسئول → انتشار → ثبت Audit و امکان بازگشت.</p></div></section></> }
function Support() { return <><section className="ma-intro"><h2>پشتیبانی و درخواست‌ها</h2><p>این صف عمداً خالی است: فرم‌های عمومی بدون مقصد BFF تأییدشده، داده تماس را ذخیره یا تیکت ساختگی ایجاد نمی‌کنند.</p></section><section className="ma-grid"><div className="ma-panel"><Headphones size={26}/><h2>درخواست بازدید و معاوضه</h2><State tone="warn">BFF و Audit لازم است</State><p>پس از اتصال، هر درخواست دارای شناسه پیگیری واقعی، محدودیت نرخ، رضایت و زمان‌بندی پاسخ خواهد بود.</p></div><div className="ma-panel"><Bell size={26}/><h2>اعلان‌ها</h2><State tone="locked">رضایت جداگانه لازم است</State><p>رضایت پاسخ به فرم، مجوز بازاریابی یا اعلان موجودی نیست.</p></div><div className="ma-panel"><UsersRound size={26}/><h2>پاسخ‌گویی مشتری</h2><State tone="locked">نقش و Audit لازم است</State><p>اپراتور فقط درخواست‌های حوزه خود را می‌بیند؛ دسترسی گسترده به قراردادها ایجاد نمی‌شود.</p></div></section><section className="ma-panel ma-callout"><CircleX size={24}/><div><h2>قانون عملیاتی</h2><p>تا زمانی که سرویس دریافت امن وصل نشده، هیچ پیامک، ایمیل، رزرو یا تغییر وضعیت واقعی از این کنسول ارسال نمی‌شود.</p></div></section></> }
function Customer() { return <><section className="ma-intro"><h2>تجربه خصوصی مشتری</h2><p>این بخش نقشه اتصال است، نه نمایشی از مشتریان واقعی. مرورگر هرگز به دیتابیس یا وضعیت داخلی زنجیره تأمین متصل نمی‌شود.</p></section><section className="ma-timeline">{[["۱", "ورود OTP", "شماره ثبت‌شده، محدودیت نرخ و رضایت"], ["۲", "کنترل مالکیت", "قرارداد و خودرو فقط برای همان مشتری"], ["۳", "Customer Read Model", "فقط وضعیت و مشخصات مجازِ انتشار"], ["۴", "رسانه و مدارک", "فضای خصوصی، اسکن فایل، لینک کوتاه‌عمر و Audit"]].map(([step, title, text]) => <div key={step}><b>{step}</b><h2>{title}</h2><p>{text}</p></div>)}</section><section className="ma-panel"><h2>قواعد انتشار</h2><div className="ma-rule-grid"><p><CircleCheck size={17}/>قرارداد، خودرو، موعد و مرحله تحویلِ مشتری‌پسند</p><p><CircleCheck size={17}/>VIN فقط بعد از تخصیص قطعی و تأیید انتشار</p><p><CircleX size={17}/>CIF، سود، نرخ ارز، VIN پیشنهادی و یادداشت داخلی</p><p><CircleX size={17}/>جزئیات تأمین‌کننده، حمل‌کننده و اطلاعات دیگر مشتریان</p></div></section></> }
function Seo() { return <><section className="ma-intro"><h2>SEO و انتشار</h2><p>مسیرهای قدیمی به‌صورت مپ‌شده نگهداری شده‌اند. ایندکس تا زمان بالا آمدن روی دامنه اصلی و بررسی Search Console بسته است.</p></section><section className="ma-grid"><div className="ma-panel"><State tone="locked">MEHR_ALLOW_INDEXING=false</State><h2>ایندکس عمومی</h2><p>robots.txt در این وضعیت مانع ایندکس است و sitemap خالی می‌ماند.</p></div><div className="ma-panel"><State tone="ok">مسیرهای قدیمی مپ شده‌اند</State><h2>مهاجرت URL</h2><p>مسیرهای تأییدشده به مقصدهای جدید ریدایرکت دائمی می‌شوند؛ دسته‌بندی حدسی ایجاد نشده است.</p></div><div className="ma-panel"><State>نیازمند تأیید</State><h2>گیت انتشار</h2><p>دامنه canonical، sitemap، Search Console، ۳۰۱/۳۰۸ و صفحات ۴۰۴ باید روی هاست واقعی بررسی شوند.</p></div></section></> }
function Security() { return <><section className="ma-intro"><h2>دسترسی و اتصال امن</h2><p>این صفحه به‌جای وانمودکردن به اتصال، مرزهای لازم برای عملیاتی‌شدن را شفاف نشان می‌دهد.</p></section><section className="ma-readiness ma-panel">{[["هویت اپراتور", "SSO یا OTP سازمانی، نشست امن و نقش سمت سرور", "locked"], ["مجوز دسترسی", "RBAC حوزه‌ای، ثبت Audit و بازبینی دوره‌ای", "locked"], ["درخواست عمومی", "BFF با مبدأ مجاز، Idempotency و Rate Limit", "warn"], ["داده مشتری", "Read Model جدا از سامانه داخلی و serializer مجاز", "locked"], ["فضای پرونده", "رمزنگاری، اسکن فایل و لینک کوتاه‌عمر", "locked"]].map(([title, detail, tone]) => <div key={title}><span className="ma-dot"/><div><strong>{title}</strong><small>{detail}</small></div><State tone={tone as "warn" | "locked"}>{tone === "warn" ? "در انتظار اتصال" : "اجباری پیش از انتشار"}</State></div>)}</section></> }
