"use client";

import Link from "next/link";
import { useState, useEffect } from "react";
import { ArrowLeft, ArrowUpLeft, Search, SlidersHorizontal, X, Download, ImageIcon, ChevronRight, ChevronLeft } from "lucide-react";
import { vehicles, brands, vehicleName, vehicleImage, faNumber, type Vehicle } from "@/lib/mehr-site/data";
import { filterVehicles, emptyFilters, type Filters } from "@/lib/mehr-site/catalog";
import tableData from "@/lib/mehr-site/technical-tables.json";
import { PageHeading, CarCard, Modal, Note, SectionHeading } from "./ui";
import { RequestForm } from "./forms";
import { CarExperienceActions } from "./selection-tools";

type ModelContext = { registerTool: (tool: { name: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean }; execute: (input: unknown) => unknown }, options: { signal: AbortSignal }) => void | Promise<void> };

export function Catalog({ initial = {}, cars = vehicles }: { initial?: Partial<Filters>; cars?: Vehicle[] }) {
  const [filters,setFilters]=useState<Filters>({...emptyFilters,...initial}),[page,setPage]=useState(1),[expanded,setExpanded]=useState(false);
  const results=filterVehicles(cars,filters),pages=Math.max(1,Math.ceil(results.length/9));
  function update(key:keyof Filters,value:string){const next={...filters,[key]:value};setFilters(next);setPage(1);const query=new URLSearchParams();Object.entries(next).forEach(([k,v])=>{if(v&&v!=="latest")query.set(k,v);});window.history.replaceState(null,"",`/mehr/cars${query.size?`?${query}`:""}`);}
  function reset(){setFilters({...emptyFilters});setPage(1);window.history.replaceState(null,"","/mehr/cars");}
  useEffect(()=>{
    const context=(document as Document&{modelContext?:ModelContext}).modelContext;
    if(!context?.registerTool)return;
    const controller=new AbortController();
    try {Promise.resolve(context.registerTool({name:"search_mehr_vehicle_catalog",description:"Read the public Mehr vehicle catalog using the same search and brand filters as the website. Does not create a request or change page state.",inputSchema:{type:"object",properties:{query:{type:"string",maxLength:150},brand:{type:"string",enum:["",...Object.keys(brands)]}},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=="object"||Array.isArray(input))throw new Error("Expected an object");const data=input as Record<string,unknown>;if(Object.keys(data).some(k=>!["query","brand"].includes(k))||data.query!==undefined&&typeof data.query!=="string"||data.brand!==undefined&&(typeof data.brand!=="string"||data.brand!==""&&!brands[data.brand]))throw new Error("Invalid catalog filters");if(typeof data.query==="string"&&data.query.length>150)throw new Error("Query too long");return filterVehicles(cars,{...emptyFilters,q:String(data.query||""),brand:String(data.brand||"")}).map(v=>({name:v.title,url:`/mehr/cars/${v.slug}`,brand:v.brand,price:"not_announced"}));}},{signal:controller.signal})).catch(()=>{});}catch{/* The catalog works normally without WebMCP support. */}
    return()=>controller.abort();
  },[cars]);
  const choices=(key:"body"|"fuel"|"gearbox"|"country"|"year")=>[...new Set(cars.flatMap(v=>v.specs[key]))].sort();
  return <><PageHeading title="خودرو، به انتخاب شما" eyebrow="THE MEHR COLLECTION" description="از میان خودروهای مهر، انتخاب نزدیک به سبک زندگی خود را پیدا کنید."><span className="ms-count-badge">{faNumber(cars.length)} خودرو <span>از {faNumber(new Set(cars.map(car=>car.brand)).size)} برند</span></span></PageHeading>
    <section className="ms-catalog"><div className="ms-catalog-bar"><label className="ms-search"><Search size={19}/><input value={filters.q} maxLength={150} onChange={e=>update("q",e.target.value)} placeholder="جست‌وجوی نام خودرو یا برند…" aria-label="جست‌وجوی خودرو"/>{filters.q&&<button aria-label="پاک‌کردن جست‌وجو" onClick={()=>update("q","")}><X size={16}/></button>}</label><label className="ms-filter-label">برند<select value={filters.brand} onChange={e=>update("brand",e.target.value)}><option value="">همه برندها</option>{Object.entries(brands).map(([id,b])=><option key={id} value={id}>{b}</option>)}</select></label><label className="ms-filter-label">کلاس خودرو<select value={filters.body} onChange={e=>update("body",e.target.value)}><option value="">همه کلاس‌ها</option>{choices("body").map(x=><option key={x}>{x}</option>)}</select></label><button className={`ms-filter-button ${expanded?"is-active":""}`} onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}><SlidersHorizontal size={18}/>فیلتر بیشتر</button></div>
    {expanded&&<div className="ms-extra-filters">{([["country","کشور"],["gearbox","گیربکس"],["fuel","سوخت"],["year","سال تولید"]] as const).map(([key,label])=><label key={key} className="ms-filter-label">{label}<select value={filters[key]} onChange={e=>update(key,e.target.value)}><option value="">همه</option>{choices(key).map(x=><option key={x}>{x}</option>)}</select></label>)}<p>قیمت خودروها نیازمند استعلام است؛ فیلتر قیمت پس از اعلام قیمت معتبر فعال می‌شود.</p></div>}
    <div className="ms-catalog-meta"><span aria-live="polite">{faNumber(results.length)} خودرو برای انتخاب شما</span><label>مرتب‌سازی<select value={filters.sort} onChange={e=>update("sort",e.target.value)}><option value="latest">تازه‌های مهر</option><option value="year-desc">سال تولید؛ جدیدتر</option><option value="year-asc">سال تولید؛ قدیمی‌تر</option><option value="name">نام خودرو</option></select></label></div>
    {Object.entries(filters).some(([k,v])=>k!=="sort"&&v)&&<div className="ms-filter-chips">{Object.entries(filters).filter(([k,v])=>k!=="sort"&&v).map(([k,v])=><button key={k} onClick={()=>update(k as keyof Filters,"")}>{k==="brand"?brands[v]:v}<X size={13}/></button>)}<button className="ms-clear-filters" onClick={reset}>پاک‌کردن همه</button></div>}
    {results.length?<div className="ms-cards">{results.slice((page-1)*9,page*9).map(car=><CarCard key={car.slug} car={car}/>)}</div>:<div className="ms-empty"><Search size={38}/><h2>خودرویی با این مشخصات پیدا نشد</h2><p>نام یا فیلترها را تغییر دهید.</p><button className="ms-button ms-button-dark" onClick={reset}>نمایش همه خودروها</button></div>}
    {pages>1&&<nav className="ms-pagination" aria-label="صفحه‌بندی خودروها"><button disabled={page===1} aria-label="صفحه قبل" onClick={()=>setPage(page-1)}><ChevronRight size={18}/></button>{Array.from({length:pages},(_,i)=><button key={i} aria-current={page===i+1?"page":undefined} onClick={()=>setPage(i+1)}>{faNumber(i+1)}</button>)}<button disabled={page===pages} aria-label="صفحه بعد" onClick={()=>setPage(page+1)}><ChevronLeft size={18}/></button></nav>}
    </section></>;
}

export function VehicleDetail({ car, cars = vehicles }: { car: Vehicle; cars?: Vehicle[] }) {
  const [tab,setTab]=useState("overview"),[request,setRequest]=useState(false),[photo,setPhoto]=useState<number|null>(null);
  const tabs=[["overview","معرفی خودرو"],["specs","مشخصات فنی"],["gallery","گالری تصاویر"],["catalog","کاتالوگ"]];
  const table=(tableData as Record<string,{caption:string;rows:string[][];sourceUrl:string}>)[car.slug];
  const related=cars.filter(v=>v.slug!==car.slug).sort((a,b)=>Number(b.brand===car.brand)-Number(a.brand===car.brand)).slice(0,3);
  return <><div className="ms-breadcrumb ms-detail-breadcrumb"><Link href="/mehr">مهر</Link><ChevronLeft size={14}/><Link href="/mehr/cars">خودروها</Link><ChevronLeft size={14}/><Link href={`/mehr/cars?brand=${car.brand}`}>{brands[car.brand]}</Link><ChevronLeft size={14}/><span>{vehicleName(car)}</span></div>
    <div className="mx-detail-tools"><CarExperienceActions slug={car.slug}/></div>
    <section className="ms-product-hero"><div className="ms-product-copy"><Link className="ms-eyebrow" href={`/mehr/cars?brand=${car.brand}`}>{car.brandName} COLLECTION</Link><h1>{vehicleName(car)}</h1><span className="ms-product-latin" dir="ltr">{car.title.split("|")[1]?.trim()||car.slug.toUpperCase()}</span><div className="ms-product-key-specs">{([["body","کلاس خودرو"],["fuel","نوع سوخت"],["gearbox","گیربکس"]]as const).map(([key,label])=><div key={key}><small>{label}</small><strong>{car.specs[key].join(" / ")||"اعلام نشده"}</strong></div>)}</div><p className="ms-price-note">برای اطلاع از قیمت و شرایط فروش، با مهر در ارتباط باشید.</p><button className="ms-button ms-button-dark" onClick={()=>setRequest(true)}>درخواست مشاوره و خرید<ArrowLeft size={20}/></button>{car.catalogUrl&&<a href={car.catalogUrl} className="ms-text-link ms-download-link" target="_blank" rel="noreferrer"><Download size={17}/>دریافت کاتالوگ خودرو</a>}</div><div className="ms-product-visual"><span>{car.brandName}</span><img src={vehicleImage(car)} alt={vehicleName(car)} fetchPriority="high" width={1024} height={512}/><button className="ms-gallery-open" onClick={()=>{setTab("gallery");document.getElementById("ms-product-content")?.scrollIntoView({behavior:"smooth"});}}><ImageIcon size={18}/>گالری تصاویر {faNumber(car.gallery.length)}</button></div></section>
    <section className="ms-product-content" id="ms-product-content"><div className="ms-tabs" role="tablist" aria-label="اطلاعات خودرو">{tabs.map(([id,label],index)=><button key={id} role="tab" id={`ms-tab-${id}`} aria-selected={tab===id} tabIndex={tab===id?0:-1} aria-controls={`ms-panel-${id}`} onClick={()=>setTab(id)} onKeyDown={e=>{if(!["ArrowRight","ArrowLeft","Home","End"].includes(e.key))return;e.preventDefault();const n=e.key==="Home"?0:e.key==="End"?tabs.length-1:(index+(e.key==="ArrowLeft"?1:-1)+tabs.length)%tabs.length;setTab(tabs[n][0]);document.getElementById(`ms-tab-${tabs[n][0]}`)?.focus();}}>{label}</button>)}</div><div className="ms-tab-panel" role="tabpanel" id={`ms-panel-${tab}`} aria-labelledby={`ms-tab-${tab}`}>
    {tab==="overview"&&<div className="ms-prose">{car.descriptionSections.length?car.descriptionSections.map((section,i)=><section key={i}><h2>{section.heading}</h2>{section.paragraphs.map((p,j)=><p key={j}>{p}</p>)}</section>):<Note>توضیحات تکمیلی را در کاتالوگ خودرو ببینید یا از کارشناسان مهر بپرسید.</Note>}<p className="ms-source-note">اطلاعات برگرفته از سایت مهر است. امکانات نهایی به تیپ و قرارداد انتخابی شما بستگی دارد.</p></div>}
    {tab==="specs"&&<><div className="ms-spec-grid">{([["country","کشور"],["year","سال تولید"],["body","کلاس"],["gearbox","گیربکس"],["fuel","نوع سوخت"],["colors","رنگ‌ها"]]as const).map(([key,label])=><div key={key}><span>{label}</span><strong>{car.specs[key].join("، ")||"اعلام نشده"}</strong></div>)}</div>{table&&<><h2 className="ms-table-title">جدول مشخصات و تجهیزات</h2>{car.slug==="corolla-cross"&&<Note>عنوان جدول در منبع با مدل دیگری مطابقت دارد؛ مشخصات نهایی این جدول نیازمند تأیید مهر است.</Note>}<div className="ms-table-wrap"><table><caption>{table.caption}</caption><tbody>{table.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=>i===0?<th key={j} scope="col">{cell}</th>:<td key={j} colSpan={row.length===1?Math.max(...table.rows.map(r=>r.length)):1}>{cell||"—"}</td>)}</tr>)}</tbody></table></div></>}{!table&&<Note>جزئیات کامل تجهیزات در متن معرفی و کاتالوگ خودرو ارائه شده است.</Note>}</>}
    {tab==="gallery"&&(car.gallery.length?<div className="ms-gallery-grid">{car.gallery.map((item,i)=><button key={item.url} onClick={()=>setPhoto(i)} aria-label={`نمایش تصویر ${faNumber(i+1)} ${vehicleName(car)}`}><img src={item.url} alt={item.alt||`${vehicleName(car)}؛ نمای ${faNumber(i+1)}`} loading="lazy" width={640} height={420}/><ImageIcon size={20}/></button>)}</div>:<Note>گالری این خودرو هنوز در منبع اضافه نشده است. تصویر اصلی و کاتالوگ در دسترس شماست.</Note>)}
    {tab==="catalog"&&(car.catalogUrl?<><a className="ms-button ms-button-dark" href={car.catalogUrl} target="_blank" rel="noreferrer"><Download size={18}/>بازکردن و دانلود کاتالوگ</a><iframe className="ms-pdf" src={car.catalogUrl} title={`کاتالوگ ${vehicleName(car)}`} loading="lazy"/><p className="ms-source-note">اگر مرورگر فایل را نمایش نمی‌دهد، از دکمه دانلود استفاده کنید.</p></>:<Note>کاتالوگ این مدل هنوز منتشر نشده است. برای دریافت مشخصات با مهر تماس بگیرید.</Note>)}
    </div></section><section className="ms-section"><SectionHeading title="انتخاب‌های دیگر مهر" href="/mehr/cars"/><div className="ms-cards">{related.map(v=><CarCard key={v.slug} car={v}/>)}</div></section>
    <Modal title={`درخواست خرید ${vehicleName(car)}`} open={request} onClose={()=>setRequest(false)}><RequestForm mode="purchase" vehicle={vehicleName(car)} source={car.pageUrl}/></Modal>
    <Modal title={`گالری ${vehicleName(car)}`} open={photo!==null} onClose={()=>setPhoto(null)} wide>{photo!==null&&<div className="ms-lightbox"><img src={car.gallery[photo]?.url} alt={car.gallery[photo]?.alt||vehicleName(car)}/><div><button aria-label="تصویر قبل" onClick={()=>setPhoto((photo-1+car.gallery.length)%car.gallery.length)}><ChevronRight/></button><span>{faNumber(photo+1)} / {faNumber(car.gallery.length)}</span><button aria-label="تصویر بعد" onClick={()=>setPhoto((photo+1)%car.gallery.length)}><ChevronLeft/></button><a href={car.gallery[photo]?.url} target="_blank" rel="noreferrer"><ArrowUpLeft size={19}/>تصویر اصلی</a></div></div>}</Modal>
  </>;
}
