"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowUpLeft, Phone, MapPin, Wrench, FileText, MessageSquare, ClipboardCheck, Headphones, ShieldCheck, Download, Search, ExternalLink } from "lucide-react";
import { entries, entryImage, entryPath, branches, documents, faDate, faNumber, rewriteContentLinks, type Entry } from "@/lib/mehr-site/data";
import { EditorialCard, PageHeading, Note, Modal, SectionHeading } from "./ui";
import { BookingForm, RequestForm } from "./forms";
import type { PageIntro } from "@/lib/mehr-site/cms-contract";

export function ContentIndex({ kind, cmsEntries }: { kind: "journal"|"news"|"services"; cmsEntries?: Entry[] }) {
  const [query,setQuery]=useState(""),[sort,setSort]=useState("date-desc");
  const type=kind==="journal"?"posts":kind==="news"?"notifications":"service";
  const source=cmsEntries||entries;
  const items=source.filter(e=>e.type===type&&e.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==="title-asc"?a.title.localeCompare(b.title,"fa"):sort==="title-desc"?b.title.localeCompare(a.title,"fa"):sort==="date-asc"?a.date.localeCompare(b.date):b.date.localeCompare(a.date));
  const titles={journal:["مجله مهر","MEHR JOURNAL","نگاهی نزدیک‌تر به خودروها، تازه‌ها و دنیای مهر."],news:["فروش و اطلاعیه‌ها","MEHR NEWSROOM","اطلاعیه‌ها و بخشنامه‌های منتشرشده مهر، همراه با اصل مستندات."],services:["همراهی، پس از هر سفر","MEHR AFTERSALES","خدمات پس از فروش مهر؛ برای رسیدگی به خودروی شما."]};
  return <><PageHeading title={titles[kind][0]} eyebrow={titles[kind][1]} description={titles[kind][2]}/><section className="ms-section ms-index-section">
    {kind!=="services"&&<div className="ms-content-controls"><label className="ms-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="جست‌وجو در مطالب" placeholder="جست‌وجو در عنوان مطالب…"/></label><label>مرتب‌سازی<select value={sort} onChange={e=>setSort(e.target.value)}><option value="date-desc">جدیدترین</option><option value="date-asc">قدیمی‌ترین</option><option value="title-asc">عنوان؛ الف تا ی</option><option value="title-desc">عنوان؛ ی تا الف</option></select></label><span aria-live="polite">{faNumber(items.length)} مطلب</span></div>}
    {kind==="news"&&<Note>اطلاعیه‌ها با تاریخ اصلی نگهداری شده‌اند. برای موجودی، قیمت و شرایط معتبر امروز با مهر تماس بگیرید.</Note>}
    <div className={kind==="services"?"ms-service-grid":"ms-editorial-grid"}>{items.map(e=>kind==="services"?<Link className="ms-service-card" key={e.id} href={entryPath(e)}><img src={entryImage(e)!} alt={e.title} width={640} height={400} loading="lazy"/><div><span className="ms-eyebrow">خدمات مهر</span><h2>{e.title}</h2><p>آشنایی با خدمت و هماهنگی مراجعه</p><span className="ms-text-link">درخواست نوبت<ArrowUpLeft size={20}/></span></div></Link>:<EditorialCard key={e.id} entry={e}/>)}</div>
    {!items.length&&<div className="ms-empty"><h2>مطلبی پیدا نشد</h2><button className="ms-button ms-button-dark" onClick={()=>setQuery("")}>نمایش همه مطالب</button></div>}
    {kind==="services"&&<div className="ms-service-contact"><Wrench size={32}/><div><h2>برای هماهنگی خدمات با ما تماس بگیرید</h2><p>مرکز خدمات مهر · رشت، خیابان شهدا، جنب بیمه دانا</p></div><a href="tel:+981333846760" className="ms-button ms-button-dark" dir="ltr">013 3384 6760 <Phone size={18}/></a></div>}
  </section></>;
}

export function ArticleDetail({ entry, cmsEntries }: { entry: Entry; cmsEntries?: Entry[] }) {
  const [comment,setComment]=useState(false),[shared,setShared]=useState(false);
  async function share(){const url=window.location.href;try{if(navigator.share)await navigator.share({title:entry.title,url});else {await navigator.clipboard.writeText(url);setShared(true);}}catch{setShared(false);}}
  const related=(cmsEntries||entries).filter(e=>e.type===entry.type&&e.id!==entry.id).slice(0,3);
  return <><PageHeading title={entry.title.split("|")[0]} eyebrow={entry.type==="posts"?"MEHR JOURNAL":"MEHR NEWSROOM"}/><div className="ms-article-meta"><span>{faDate(entry.date)}</span><span>مهر خودرو</span><button onClick={share} className="ms-text-link">{shared?"پیوند کپی شد":"اشتراک‌گذاری"}<ArrowUpLeft size={16}/></button></div><article className={`ms-article ${entry.type==="notifications"?"ms-notice-article":""}`}>
    {entryImage(entry)&&<img className="ms-article-hero" src={entryImage(entry)!} alt={entry.title} width={1200} height={675}/>}
    {entry.type==="notifications"&&<Note>این سند مربوط به تاریخ انتشار بالاست و اعلام فروش فعال امروز نیست. شرایط جاری را از کارشناسان مهر استعلام کنید.</Note>}
    {entry.contentWarning&&entry.type==="posts"&&<Note>این مطلب آرشیوی است؛ اطلاعات و شرایط نهایی را پیش از تصمیم با مهر بررسی کنید.</Note>}
    <div className="ms-prose ms-article-body" dangerouslySetInnerHTML={{__html:rewriteContentLinks(entry.bodyHtml)}}/>
    {entry.pdfAttachments.map(pdf=><a key={pdf} className="ms-button ms-button-dark" href={pdf} target="_blank" rel="noreferrer"><Download size={18}/>دریافت فایل اصلی</a>)}
    <div className="ms-article-source"><a href={entry.sourceUrl} target="_blank" rel="noreferrer">مشاهده نسخه منبع<ExternalLink size={14}/></a><span>تاریخ‌ها و مطالب از آرشیو مهر منتقل شده‌اند.</span></div>
    <section className="ms-comments"><SectionHeading title="دیدگاه شما"/>{entry.publicComments.map((c,i)=><div className="ms-comment" key={i}><span className="ms-comment-avatar">{c.displayName.slice(0,1)}</span><div><strong>{c.displayName}</strong><small>{faDate(c.date)}</small><p>{c.text}</p></div></div>)}{!entry.publicComments.length&&<p>شما اولین دیدگاه را بنویسید.</p>}<button className="ms-button ms-button-outline" onClick={()=>setComment(true)}>نوشتن دیدگاه<MessageSquare size={18}/></button></section>
  </article><section className="ms-section"><SectionHeading title="برای مطالعه بیشتر" href={entry.type==="posts"?"/mehr/journal":"/mehr/news"}/><div className="ms-editorial-grid">{related.map(e=><EditorialCard key={e.id} entry={e}/>)}</div></section><Modal title="دیدگاه شما" open={comment} onClose={()=>setComment(false)}><RequestForm mode="comment" source={entry.sourceUrl}/></Modal></>;
}

export function ServiceDetail({ entry, cmsEntries }: { entry: Entry; cmsEntries?: Entry[] }) {
  return <><PageHeading title={entry.title} eyebrow="MEHR AFTERSALES" description="برای هماهنگی مراجعه، خدمت مورد نظر و مشخصات خودرو را با ما در میان بگذارید."/><section className="ms-service-detail"><div className="ms-service-intro">{entryImage(entry)&&<img src={entryImage(entry)!} alt={entry.title} width={700} height={560}/>}<h2>خدمات {entry.title} در مهر</h2><p>برای اطلاع از جزئیات این خدمت، زمان مراجعه و تعرفه متناسب با خودروی شما، با مرکز خدمات مهر هماهنگ کنید.</p><div className="ms-contact-line"><Phone size={20}/><a href="tel:+981333846760" dir="ltr">013 3384 6760</a></div><p className="ms-muted">رشت، خیابان شهدا، جنب بیمه دانا</p></div><BookingForm service={entry.title}/></section><section className="ms-section"><SectionHeading title="خدمات دیگر مهر" href="/mehr/services"/><div className="ms-service-links">{(cmsEntries||entries).filter(e=>e.type==="service"&&e.id!==entry.id).map(e=><Link key={e.id} href={entryPath(e)}>{e.title}<ArrowUpLeft size={20}/></Link>)}</div></section></>;
}

export function ContactPage({ intro }: { intro?: PageIntro }){const heading=intro||{title:"از نزدیک، در کنار شما",eyebrow:"MEET MEHR",description:"برای انتخاب خودرو، خدمات یا پیگیری درخواست، با شعب مهر در ارتباط باشید."};return <><PageHeading {...heading}/><section className="ms-section ms-index-section"><div className="ms-branch-grid">{branches.map((b,i)=><div className="ms-branch-card" key={b.name}><span className="ms-branch-number">0{i+1}</span><span className="ms-eyebrow">{b.tag}</span><h2>{b.name}</h2><p><MapPin size={18}/>{b.address}</p><a className="ms-branch-phone" href={`tel:+98${b.phone.slice(1)}`} dir="ltr">{b.phone}<Phone size={18}/></a><a className="ms-text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(b.query)}`} target="_blank" rel="noreferrer">مسیریابی<ArrowUpLeft size={18}/></a></div>)}</div><div className="ms-contact-grid"><div><span className="ms-eyebrow">صدای شما برای ما مهم است</span><h2>با مهر گفتگو کنید</h2><p>سؤال یا درخواست خود را با ما در میان بگذارید.</p><div className="ms-social-links"><a href="https://wa.me/989120534206" target="_blank" rel="noreferrer">واتس‌اپ<ArrowUpLeft size={18}/></a><a href="https://t.me/mehrkhodro_co" target="_blank" rel="noreferrer">تلگرام<ArrowUpLeft size={18}/></a><a href="https://instagram.com/mehrkhodro.co" target="_blank" rel="noreferrer">اینستاگرام<ArrowUpLeft size={18}/></a></div><iframe className="ms-map" title="موقعیت مهر خودرو در رشت" src="https://maps.google.com/maps?q=Rasht%2CIran%2C%20MEHR%20KHODRO&t=m&z=13&output=embed&iwloc=near" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><RequestForm/></div></section></>;}

const customerLinks=[{title:"حقوق مشتریان",description:"راهنما و دریافت آیین‌نامه",path:"rights",icon:ShieldCheck},{title:"نظرسنجی مشتریان",description:"تجربه شما از خدمات مهر",path:"survey",icon:ClipboardCheck},{title:"ثبت و پیگیری شکایت",description:"دریافت فرم و ارتباط با مسئولان",path:"complaints",icon:MessageSquare},{title:"ارتباط با مشتریان",description:"همراهی در مسیر درخواست شما",path:"communication",icon:Headphones},{title:"راه‌های ارتباطی",description:"شماره تماس و نشانی شعب",path:"contact",icon:Phone},{title:"تبدیل پلاک",description:"راهنما و درخواست تبدیل پلاک",path:"numberplate",icon:FileText}];
export function CustomerPage({ section }: { section?:string }){
  if(section==="survey"||section==="complaints")return <><PageHeading title={section==="survey"?"تجربه شما، مسیر بهتر ما":"صدای شما شنیده می‌شود"} eyebrow="MEHR CUSTOMER CARE" description={section==="survey"?"فرم نظرسنجی خدمات مهر را دریافت و تکمیل کنید.":"فرم شکایت مشتریان و راه‌های ارتباط با مهر در اختیار شماست."}/><section className="ms-document-section"><div className="ms-document-heading"><FileText size={38}/><div><h2>{section==="survey"?"پرسش‌نامه رضایت مشتریان":"فرم شکایت مشتریان"}</h2><p>{section==="survey"?"۲ صفحه · ۲۲ پرسش":"۱ صفحه · اطلاعات مشتری و شرح شکایت"}</p></div><a className="ms-button ms-button-dark" href={documents[section]} target="_blank" rel="noreferrer">دریافت فرم<Download size={18}/></a></div><Note>این سند چاپی است. برای تحویل فرم و پیگیری، با مهر تماس بگیرید. اطلاعاتی از طریق این صفحه ارسال نمی‌شود.</Note><iframe className="ms-pdf" src={documents[section]} title={section==="survey"?"پرسش‌نامه نظرسنجی مهر":"فرم شکایت مهر"}/><div className="ms-form-actions"><a className="ms-text-link" href="tel:+981334206"><Phone size={17}/>تماس با امور مشتریان</a><Link className="ms-text-link" href="/mehr/customers">بازگشت به امور مشتریان<ArrowLeft size={17}/></Link></div></section></>;
  if(section==="rights"||section==="communication")return <><PageHeading title={section==="rights"?"حقوق مشتریان مهر":"ارتباط با مشتریان"} eyebrow="MEHR CUSTOMER CARE"/><section className="ms-section"><div className="ms-care-callout"><ShieldCheck size={48}/><h2>{section==="rights"?"اطلاعات روشن، ارتباط مستقیم":"برای پیگیری، با مهر در ارتباط باشید"}</h2><p>{section==="rights"?"برای دریافت نسخه معتبر آیین‌نامه حقوق مشتریان و راهنمای مرتبط با قرارداد خود، با واحد امور مشتریان مهر تماس بگیرید.":"برای راهنمایی درباره درخواست‌ها، خدمات یا مدارک مورد نیاز با همکاران ما تماس بگیرید."}</p><a className="ms-button ms-button-dark" href="tel:+981334206">تماس با مهر<Phone size={18}/></a><Note>در این نسخه ورود مشتری یا رهگیری آنلاین فعال نشده است.</Note></div></section></>;
  return <><PageHeading title="مهر، در کنار شماست" eyebrow="MEHR CUSTOMER CARE" description="راهی روشن برای ارتباط، بیان تجربه و پیگیری درخواست‌های شما."/><section className="ms-section ms-index-section"><div className="ms-care-grid">{customerLinks.map(item=><Link href={`/mehr/${item.path}`} key={item.path}><item.icon size={30}/><h2>{item.title}</h2><p>{item.description}</p><ArrowUpLeft size={23}/></Link>)}</div><div className="ms-service-contact"><Headphones size={38}/><div><h2>پاسخ سؤال خود را پیدا نکردید؟</h2><p>با همکاران مهر گفتگو کنید.</p></div><Link href="/mehr/contact" className="ms-button ms-button-dark">راه‌های ارتباط<ArrowLeft size={18}/></Link></div></section></>;
}

export function AboutPage({ intro, cmsEntries }: { intro?: PageIntro; cmsEntries?: Entry[] }){const entry=(cmsEntries||entries).find(e=>e.slug==="about-us")||entries.find(e=>e.slug==="about-us")!;const heading=intro||{title:"مهر؛ نامی برای همراهی",eyebrow:"THE MEHR STORY",description:"از سال ۱۳۹۱، در مسیر انتخاب و نگهداری خودرو."};return <><PageHeading {...heading}/><section className="ms-about-story"><div><span className="ms-about-year">۱۳۹۱</span><span className="ms-eyebrow">آغاز مسیر مهر</span><div className="ms-prose" dangerouslySetInnerHTML={{__html:rewriteContentLinks(entry.bodyHtml)}}/><Link className="ms-button ms-button-dark" href="/mehr/contact">از نزدیک با مهر آشنا شوید<ArrowLeft size={18}/></Link></div><img src={entryImage(entry)!} alt="تویوتا هایلوکس، از خودروهای مجموعه مهر" width={950} height={750}/></section><section className="ms-about-values"><div><ShieldCheck/><h2>انتخاب با شناخت</h2><p>دسترسی به مشخصات و کاتالوگ، پیش از تصمیم برای خرید.</p></div><div><Wrench/><h2>همراهی پس از خرید</h2><p>راه ارتباط مستقیم با خدمات پس از فروش مهر.</p></div><div><MapPin/><h2>حضور در کنار شما</h2><p>شوروم، مرکز خدمات و دفتر مرکزی در رشت و منطقه آزاد انزلی.</p></div></section></>;}

export function NumberplatePage({ cmsEntries }: { cmsEntries?: Entry[] }){const [open,setOpen]=useState(false);const entry=(cmsEntries||entries).find(e=>e.slug==="register-numberplate")||entries.find(e=>e.slug==="register-numberplate")!;return <><PageHeading title="از پلاک منطقه آزاد، تا پلاک ملی" eyebrow="MEHR SERVICES" description="راهنما و درخواست بررسی شرایط تبدیل پلاک خودرو."/><section className="ms-numberplate-layout"><article className="ms-prose"><Note>این راهنما از مطلب منتشرشده در {faDate(entry.date)} منتقل شده است. شرایط و ضوابط جاری باید پیش از اقدام از مهر استعلام شود.</Note><div dangerouslySetInnerHTML={{__html:rewriteContentLinks(entry.bodyHtml)}}/></article><aside className="ms-numberplate-card"><FileText size={42}/><h2>شرایط خودروی شما چیست؟</h2><p>مشخصات خودرو را برای درخواست راهنمایی آماده کنید.</p><ul><li>برند و مدل خودرو</li><li>سال ساخت</li><li>اطلاعات تماس شما</li></ul><button className="ms-button ms-button-red" onClick={()=>setOpen(true)}>فرم درخواست تبدیل پلاک<ArrowLeft size={18}/></button><a className="ms-text-link" href="tel:+981334206"><Phone size={17}/>تماس با کارشناسان مهر</a></aside></section><Modal title="درخواست تبدیل پلاک" open={open} onClose={()=>setOpen(false)}><RequestForm mode="numberplate" source={entry.sourceUrl}/></Modal></>;}
