"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight, Expand, Printer, RotateCcw, Wallet, ImageIcon } from "lucide-react";
import { vehicles, vehicleName, vehicleImage, faNumber } from "@/lib/mehr-site/data";
import { calculateBudget, parseAmount } from "@/lib/mehr-site/experience";
import { Modal, Note, PageHeading } from "./ui";
import { VehicleActions } from "./garage-store";

function VehiclePicker({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <label className="mx-vehicle-picker">مدل خودرو<select value={value} onChange={event => onChange(event.target.value)}>{vehicles.map(car => <option value={car.slug} key={car.slug}>{vehicleName(car)}</option>)}</select></label>;
}

export function Showroom({ initialCar }: { initialCar: string }) {
  const [slug, setSlug] = useState(initialCar || "camry");
  const [angle, setAngle] = useState(0), [zoom, setZoom] = useState(false), [detail, setDetail] = useState("body");
  const [color, setColor] = useState("");
  const car = vehicles.find(vehicle => vehicle.slug === slug) || vehicles[0];
  const gallery = [{ url: vehicleImage(car), alt: `تصویر اصلی ${vehicleName(car)}` }, ...car.gallery];
  const active = gallery[angle];
  const details = [{ id: "body", title: "طراحی بدنه", value: car.specs.body.join(" / ") }, { id: "fuel", title: "قوای محرکه", value: `${car.specs.fuel.join(" / ")} · ${car.specs.gearbox.join(" / ")}` }, { id: "catalog", title: "تجهیزات و کابین", value: "تجهیزات به تیپ خودرو وابسته‌اند؛ مشخصات کامل را در کاتالوگ بررسی کنید." }];
  function move(amount: number) { setAngle(current => (current + amount + gallery.length) % gallery.length); }
  return <><PageHeading title="مهر، از نزدیک" eyebrow="EXPLORE THE DETAILS" description="بین تصاویر جابه‌جا شوید و مشخصات هر مدل را بررسی کنید."/><section className="mx-workspace">
    <div className="mx-showroom-top"><VehiclePicker value={car.slug} onChange={value => { setSlug(value); setAngle(0); setColor(""); }}/><VehicleActions slug={car.slug}/></div>
    <div className="mx-showroom"><div className="mx-gallery-stage"><div className="mx-stage-heading"><span>{car.brandName}</span><b>{vehicleName(car)}</b></div><div className="mx-gallery-main" tabIndex={0} role="group" aria-label="تصاویر خودرو؛ با کلیدهای چپ و راست جابه‌جا شوید" onKeyDown={event => { if (event.key === "ArrowLeft" || event.key === "ArrowRight") { event.preventDefault(); move(event.key === "ArrowLeft" ? 1 : -1); } }}>
      <img key={`${slug}-${angle}`} src={active.url} alt={active.alt || `${vehicleName(car)}؛ تصویر ${faNumber(angle + 1)}`} width={1100} height={650} onError={event => { if (!event.currentTarget.dataset.fallback) { event.currentTarget.dataset.fallback = "true"; event.currentTarget.src = vehicleImage(car); event.currentTarget.alt = "تصویر انتخاب‌شده در دسترس نیست؛ تصویر اصلی خودرو"; } }}/>
      <button className="mx-gallery-prev" aria-label="تصویر قبل" disabled={gallery.length < 2} onClick={() => move(-1)}><ChevronRight/></button><button className="mx-gallery-next" aria-label="تصویر بعد" disabled={gallery.length < 2} onClick={() => move(1)}><ChevronLeft/></button><button className="mx-gallery-zoom" onClick={() => setZoom(true)}><Expand size={18}/>بزرگ‌نمایی</button>
    </div><div className="mx-gallery-counter"><ImageIcon size={17}/><span aria-live="polite">تصویر {faNumber(angle + 1)} از {faNumber(gallery.length)}</span><span>تصاویر کاتالوگ، نه موجودی تأییدشده</span></div><div className="mx-thumbnails" aria-label="انتخاب تصویر">{gallery.map((image, index) => <button key={`${image.url}-${index}`} onClick={() => setAngle(index)} aria-label={`انتخاب تصویر ${faNumber(index + 1)}`} aria-pressed={angle === index}><img src={image.url} alt="" width={130} height={85} loading="lazy"/></button>)}</div></div>
    <aside className="mx-showroom-details"><span className="ms-eyebrow">جزئیات انتخاب شما</span><h2>{vehicleName(car)}</h2><div className="mx-detail-tabs">{details.map(item => <button key={item.id} aria-pressed={detail === item.id} onClick={() => setDetail(item.id)}>{item.title}</button>)}</div><p className="mx-spec-value" aria-live="polite">{details.find(item => item.id === detail)?.value || "اعلام نشده"}</p><fieldset className="mx-color-choice"><legend>رنگ مورد علاقه برای مشاوره</legend>{car.specs.colors.map(item => <button type="button" key={item} aria-pressed={color === item} onClick={() => setColor(item)}>{item}</button>)}</fieldset><p className="mx-muted">انتخاب رنگ، فقط ترجیح شماست؛ رنگ تصاویر تغییر نمی‌کند و موجودی رنگ تأیید نشده است.</p><Link className="ms-button ms-button-dark" href={`/mehr/visit?car=${car.slug}${color ? `&color=${encodeURIComponent(color)}` : ""}`}>هماهنگی بازدید<ArrowLeft size={18}/></Link><Link className="ms-text-link" href={`/mehr/cars/${car.slug}`}>مشخصات کامل خودرو<ArrowLeft size={17}/></Link>{car.catalogUrl && <a className="ms-text-link" href={car.catalogUrl} target="_blank" rel="noreferrer">کاتالوگ رسمی</a>}</aside></div>
    <Note>گردش ۳۶۰ درجه و ویدیوی اختصاصی پس از تهیه و تأیید محتوای همان مدل فعال می‌شوند. این گالری، نمای ۳۶۰ درجه یا ویدیوی خودروی تخصیص‌یافته نیست.</Note>
    <Modal title={vehicleName(car)} open={zoom} onClose={() => setZoom(false)} wide><div className="ms-lightbox"><img src={active.url} alt={active.alt || vehicleName(car)}/><div><button aria-label="تصویر قبل" onClick={() => move(-1)}><ChevronRight/></button><span>{faNumber(angle + 1)} / {faNumber(gallery.length)}</span><button aria-label="تصویر بعد" onClick={() => move(1)}><ChevronLeft/></button></div></div></Modal>
  </section></>;
}

export function PurchasePlan({ initialCar }: { initialCar: string }) {
  const [slug, setSlug] = useState(initialCar || "camry");
  const [values, setValues] = useState({ price: "", down: "0", trade: "0", extra: "0", months: "12" });
  const car = vehicles.find(vehicle => vehicle.slug === slug) || vehicles[0];
  const numbers = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, parseAmount(value)])) as { price: number; down: number; trade: number; extra: number; months: number };
  const plan = calculateBudget(numbers);
  return <><PageHeading title="برنامه خرید شما" eyebrow="PLAN YOUR NEXT CAR" description="با ارقام خودتان، مبلغ باقی‌مانده و تقسیم پرداخت‌ها را محاسبه کنید."/><section className="mx-workspace mx-print-area"><Note>محاسبه شخصی؛ نه قیمت مهر، پیشنهاد فروش، اعتبارسنجی یا طرح اقساطی مصوب. مبلغ‌ها به تومان‌اند؛ نرخ تأمین مالی و هزینه‌های اعلام‌نشده محاسبه نمی‌شوند.</Note>
    <div className="mx-plan-layout"><form className="mx-panel ms-form" onSubmit={event => event.preventDefault()}><div className="mx-panel-heading"><Wallet/><h2>فرض‌های محاسبه</h2></div><VehiclePicker value={car.slug} onChange={value => { setSlug(value); setValues({ price: "", down: "0", trade: "0", extra: "0", months: "12" }); }}/><div className="ms-form-grid">{([['price', 'قیمت واردشده توسط شما'], ['down', 'پیش‌پرداخت نقدی'], ['trade', 'ارزش برآوردی خودروی معاوضه'], ['extra', 'هزینه‌های دیگرِ معلوم']] as const).map(([key, label]) => <label key={key}>{label} (تومان)<input inputMode="numeric" dir="ltr" maxLength={18} value={values[key]} onChange={event => setValues({ ...values, [key]: event.target.value })} placeholder={key === "price" ? "قیمت را وارد کنید" : "۰"}/></label>)}<label>تعداد پرداخت ماهانه<select value={values.months} onChange={event => setValues({ ...values, months: event.target.value })}>{[1, 3, 6, 12, 18, 24, 36, 48, 60].map(months => <option key={months} value={months}>{faNumber(months)} ماه</option>)}</select></label></div><button className="mx-secondary" type="button" onClick={() => setValues({ price: "", down: "0", trade: "0", extra: "0", months: "12" })}><RotateCcw size={16}/>پاک‌کردن ارقام</button><p className="mx-muted">تمام ارقام فقط در همین صفحه محاسبه می‌شوند و ذخیره یا ارسال نمی‌شوند.</p></form>
    <aside className="mx-plan-summary"><span className="ms-eyebrow">برآورد شخصی شما</span><img src={vehicleImage(car)} width={600} height={300} alt={vehicleName(car)}/><h2>{vehicleName(car)}</h2>{plan ? <div aria-live="polite"><div className="mx-plan-total"><span>پرداخت ماهانه بدون سود و کارمزد</span><strong>{faNumber(plan.installment)} <small>تومان</small></strong></div><dl><div><dt>قیمت واردشده</dt><dd>{faNumber(numbers.price)}</dd></div><div><dt>هزینه‌های معلوم</dt><dd>{faNumber(numbers.extra)}</dd></div><div><dt>مجموع قیمت و هزینه معلوم</dt><dd>{faNumber(plan.total)}</dd></div><div><dt>پیش‌پرداخت نقدی</dt><dd>{faNumber(numbers.down)}</dd></div><div><dt>ارزش معاوضه واردشده</dt><dd>{faNumber(numbers.trade)}</dd></div><div><dt>مانده قابل تقسیم</dt><dd>{faNumber(plan.balance)}</dd></div><div><dt>تعداد پرداخت</dt><dd>{faNumber(numbers.months)}</dd></div><div><dt>آخرین پرداخت با تعدیل گردکردن</dt><dd>{faNumber(plan.finalInstallment)}</dd></div></dl><p>این برگه تعهد فروش یا تأیید ارزش خودروی کارکرده نیست. سود و کارمزد احتمالی و شرایط واقعی فروش باید جداگانه از مهر دریافت شود.</p><button className="ms-button ms-button-dark" onClick={() => window.print()}><Printer size={18}/>چاپ / ذخیره برآورد به PDF</button></div> : <div className="mx-plan-placeholder" role="status"><h3>{values.price ? "ارقام را بررسی کنید" : "از قیمت مورد نظر شروع کنید"}</h3><p>{values.price ? "مبلغ‌ها باید عدد صحیح و غیرمنفی باشند. مجموع پیش‌پرداخت و معاوضه نباید از قیمت به‌علاوه هزینه‌ها بیشتر شود؛ سقف محاسبه هزار میلیارد تومان است." : "پس از واردکردن قیمت، نتیجه محاسبه اینجا نمایش داده می‌شود."}</p></div>}<Link className="ms-text-link" href={`/mehr/trade-in?car=${car.slug}`}>بررسی خودروی معاوضه<ArrowLeft size={17}/></Link><Link className="ms-text-link" href={`/mehr/visit?car=${car.slug}`}>دریافت شرایط واقعی از مهر<ArrowLeft size={17}/></Link></aside></div>
  </section></>;
}
