import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { importTopicSlugs, importTopics, type ImportTopicSlug } from "@/lib/mehr-site/import-guides";
import { cmsImportGuide } from "@/lib/mehr-site/cms-db";

type Props = { params: Promise<{ topic: string }> };
export const dynamic = "force-dynamic";
export function generateStaticParams() { return importTopicSlugs.map(topic => ({ topic })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { topic } = await params; if (!(topic in importTopics)) return {}; const guide = cmsImportGuide(topic, importTopics[topic as ImportTopicSlug]); return { title: guide.title, description: guide.description, keywords: [guide.title, `خودرو وارداتی ${guide.name}`, "واردات خودرو صفر", "واردات خودرو کارکرده", "ضوابط واردات خودرو", "پلاک منطقه آزاد", "پلاک ملی"], alternates: { canonical: `/mehr/import/${topic}` } }; }
export default async function ImportGuide({ params }: Props) { const { topic } = await params; if (!(topic in importTopics)) notFound(); const guide = cmsImportGuide(topic, importTopics[topic as ImportTopicSlug]); const isNational = topic === "national"; const isResidents = topic === "residents"; return <main className="mi-page"><article className="mi-article"><nav><Link href="/mehr">مهر خودرو</Link><span>/</span><Link href="/mehr/import">راهنمای واردات</Link><span>/</span><b>{guide.name}</b></nav><span className="mi-label">{guide.service ? "MEHR ANZALI" : "GENERAL GUIDANCE"}</span><h1>{guide.title}</h1><p className="mi-lead">{guide.description}</p>{guide.service ? <section className="mi-note"><h2>مهر خودرو در منطقه آزاد انزلی</h2><p>مهر خودرو، بر اساس معرفی سایت رسمی خود، اولین شرکت دارای مجوز در دور جدید واردات خودرو به منطقه آزاد انزلی و واردکننده مجاز خودرو در این منطقه است. این گزاره به منطقه آزاد انزلی محدود است و به سایر مناطق آزاد تعمیم داده نمی‌شود.</p><Link href="/mehr/cars">دیدن خودروهای مهر ←</Link></section> : <section className="mi-note"><h2>پیش از هر تصمیم</h2><p>ضوابط واردات، ثبت سفارش، شرایط تردد، حقوق و عوارض و امکان پلاک‌گذاری به منطقه، نوع خودرو، مشخصات متقاضی و تاریخ اجرا وابسته است. این صفحه مشاوره حقوقی، گمرکی یا تضمین خدمت در {guide.name} نیست.</p></section>}<section><h2>{isResidents ? "بررسی واردات برای مقیمان خارج" : isNational ? "بررسی مسیر پلاک ملی" : `بررسی واردات خودرو با پلاک منطقه آزاد ${guide.name}`}</h2><ol><li>آخرین ضوابط رسمی همان منطقه یا مسیر واردات را از مرجع ذی‌صلاح بررسی کنید.</li><li>وضعیت خودرو، سال ساخت، استانداردها، مدارک مالکیت و شرایط متقاضی را با ضابطه مؤثر تطبیق دهید.</li><li>هزینه‌ها و زمان‌بندی را فقط با مدارک و استعلام معتبر محاسبه کنید؛ اطلاعات این صفحه جایگزین آن نیست.</li><li>برای خودروهای معرفی‌شده در مهر، مشخصات عمومی و راه ارتباطی را از صفحات خود مهر بررسی کنید.</li></ol></section><section><h2>پرسش‌های رایج</h2><details><summary>آیا ضوابط همه مناطق آزاد یکسان است؟</summary><p>خیر. مسیر، منطقه، ویژگی خودرو، وضعیت متقاضی و تاریخ مؤثر می‌توانند نتیجه را تغییر دهند.</p></details><details><summary>آیا این صفحه ارائه خدمت مهر در {guide.name} را تأیید می‌کند؟</summary><p>{guide.service ? "خدمات و راه‌های ارتباطی مهر برای منطقه آزاد انزلی در سایت مهر معرفی شده‌اند." : "خیر. این صفحه فقط راهنمای عمومی برای جست‌وجوی دقیق‌تر است."}</p></details></section></article></main>; }
