import { NextResponse } from "next/server";
import { DatabaseSync } from "node:sqlite";
import { join, extname } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { getAdminSession, hasAdminPermission } from "@/lib/mehr-site/admin-auth";

const dbPath = process.env.MEHR_CMS_DATABASE_PATH || join(process.cwd(), "data", "mehr-cms.local.db");
const mediaDir = join(process.cwd(), "data", "cms-media");
const allowed = new Map([["image/jpeg", ".jpg"], ["image/png", ".png"], ["image/webp", ".webp"], ["application/pdf", ".pdf"]]);
export async function GET() { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (!hasAdminPermission(session, "readCms")) return NextResponse.json({ error: "forbidden" }, { status: 403 }); const db = new DatabaseSync(dbPath); try { return NextResponse.json({ media: db.prepare("SELECT id,storage_key,mime_type,bytes,alt_text,rights_status,status,created_at FROM cms_media ORDER BY created_at DESC").all() }); } finally { db.close(); } }
export async function POST(request: Request) { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (!hasAdminPermission(session, "manageMedia")) return NextResponse.json({ error: "forbidden" }, { status: 403 }); if (process.env.NODE_ENV === "production" && process.env.MEHR_ADMIN_CONTENT_WRITES !== "true") return NextResponse.json({ error: "writes_disabled" }, { status: 409 }); const form = await request.formData(); const file = form.get("file"); const alt = String(form.get("alt") || "").trim().slice(0, 300); const rights = String(form.get("rights") || "approved_public").trim().slice(0, 32); if (!(file instanceof File) || !allowed.has(file.type) || file.size < 1 || file.size > 10 * 1024 * 1024) return NextResponse.json({ error: "invalid_public_media" }, { status: 400 }); const id = randomUUID(), extension = allowed.get(file.type) || extname(file.name), key = `${id}${extension}`; await mkdir(mediaDir, { recursive: true }); await writeFile(join(mediaDir, key), Buffer.from(await file.arrayBuffer())); const db = new DatabaseSync(dbPath); try { const now = new Date().toISOString(); db.prepare("INSERT INTO cms_media (id,storage_key,mime_type,bytes,alt_text,rights_status,status,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)").run(id, key, file.type, file.size, alt || null, rights, "draft", session.username, now); db.prepare("INSERT INTO cms_audit_events (id,actor_id,action,entity_type,entity_id,created_at) VALUES (?,?,?,?,?,?)").run(randomUUID(), session.username, "media_uploaded", "media", id, now); return NextResponse.json({ id, key, status: "draft" }, { status: 201 }); } finally { db.close(); } }
export async function PATCH(request: Request) { const session = await getAdminSession(); if (!session) return NextResponse.json({ error: "unauthorized" }, { status: 401 }); if (!hasAdminPermission(session, "manageMedia")) return NextResponse.json({ error: "forbidden" }, { status: 403 }); if (process.env.NODE_ENV === "production" && process.env.MEHR_ADMIN_CONTENT_WRITES !== "true") return NextResponse.json({ error: "writes_disabled" }, { status: 409 }); const input = await request.json().catch(() => null) as Record<string, unknown> | null; const id = typeof input?.id === "string" ? input.id : ""; const status = typeof input?.status === "string" ? input.status : ""; const alt = typeof input?.alt === "string" ? input.alt.trim().slice(0, 300) : null; const rights = typeof input?.rights === "string" ? input.rights.trim().slice(0, 32) : null; if (!/^[a-z0-9-]{8,80}$/i.test(id) || !["draft", "published", "archived"].includes(status)) return NextResponse.json({ error: "invalid" }, { status: 400 }); if (status === "published" && !hasAdminPermission(session, "publishContent")) return NextResponse.json({ error: "publish_forbidden" }, { status: 403 }); const db = new DatabaseSync(dbPath); try { const previous = db.prepare("SELECT status,alt_text,rights_status FROM cms_media WHERE id=?").get(id) as { status: string; alt_text: string | null; rights_status: string } | undefined; if (!previous) return NextResponse.json({ error: "not_found" }, { status: 404 }); db.prepare("UPDATE cms_media SET status=?,alt_text=COALESCE(?,alt_text),rights_status=COALESCE(?,rights_status) WHERE id=?").run(status, alt, rights, id); db.prepare("INSERT INTO cms_audit_events (id,actor_id,action,entity_type,entity_id,before_json,after_json,created_at) VALUES (?,?,?,?,?,?,?,?)").run(randomUUID(), session.username, status === "published" ? "media_published" : "media_updated", "media", id, JSON.stringify(previous), JSON.stringify({ status, alt, rights }), new Date().toISOString()); return NextResponse.json({ id, status }); } finally { db.close(); } }
