import "server-only";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { cmsNavigation, replaceCmsNavigation } from "./cms-db";

export type NavItem = { id: string; label: string; href: string; status: "draft" | "published"; order: number };
export type SiteManagement = { revision: number; updatedAt: string; mainNavigation: NavItem[]; footerNavigation: NavItem[]; audit: { at: string; actor: string; action: string }[] };
const path = join(process.cwd(), "data", "mehr-site-management.json");
const defaults: SiteManagement = { revision: 1, updatedAt: "", mainNavigation: [{ id: "cars", label: "خودروها", href: "/mehr/cars", status: "published", order: 10 }, { id: "news", label: "فروش و اطلاعیه‌ها", href: "/mehr/news", status: "published", order: 20 }, { id: "services", label: "خدمات پس از فروش", href: "/mehr/services", status: "published", order: 30 }, { id: "about", label: "درباره مهر", href: "/mehr/about", status: "published", order: 40 }, { id: "journal", label: "مجله مهر", href: "/mehr/journal", status: "published", order: 50 }], footerNavigation: [], audit: [] };
export async function getSiteManagement() { try { const value = JSON.parse(await readFile(path, "utf8")); return { ...defaults, ...value, mainNavigation: cmsNavigation() }; } catch { return { ...defaults, mainNavigation: cmsNavigation() }; } }
function validItem(item: unknown): item is NavItem { if (!item || typeof item !== "object") return false; const value = item as Record<string, unknown>; return typeof value.id === "string" && /^[a-z0-9-]{2,80}$/.test(value.id) && typeof value.label === "string" && value.label.trim().length > 0 && value.label.length <= 60 && typeof value.href === "string" && value.href.startsWith("/") && value.href.length <= 250 && (value.status === "draft" || value.status === "published") && Number.isInteger(value.order); }
export async function saveNavigation(items: unknown, actor: string) { if (!Array.isArray(items) || !items.every(validItem) || new Set(items.map(item => item.id)).size !== items.length) throw new Error("invalid_navigation"); if (process.env.NODE_ENV === "production" && process.env.MEHR_ADMIN_CONTENT_WRITES !== "true") throw new Error("writes_disabled"); const current = await getSiteManagement(); const mainNavigation = replaceCmsNavigation(items.sort((a, b) => a.order - b.order), actor); return { ...current, revision: current.revision + 1, updatedAt: new Date().toISOString(), mainNavigation, audit: [{ at: new Date().toISOString(), actor, action: "main_navigation_updated" }, ...current.audit].slice(0, 100) }; }
